name: Daily Stock Data Sync (Backend)

on:
  schedule:
    - cron: '0 1 * * *' # Corre a la 1 AM UTC todos los días (después del cierre del mercado)
  workflow_dispatch: # Permite correrlo manualmente desde la pestaña "Actions"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Extraer código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './scripts/package-lock.json' # Opcional si hay lockfile

      - name: Instalar dependencias
        working-directory: ./scripts
        run: npm install

      - name: Descargar API y Actualizar Nube
        working-directory: ./scripts
        env:
          API_KEY: ${{ secrets.API_KEY }} 
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: node update-data.js
